[package]
name = "javy_chainlink_sdk"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
javy-plugin-api = "3.1.0"
javy = "4.0.0"
serde_json = "1.0"
base64 = "0.21"
rand = "0.8"
rand_chacha = "0.3"

sxt-proof-of-sql-sdk = { git="https://github.com/spaceandtimefdn/sxt-proof-of-sql-sdk", default-features=false, features=["hyperkzg"], rev="840c1bb117e343f40e2de9040b4c0b53852be78d"}